// src/components/AllBoxItem/constants/jobData.js

export const jobListings = [
  {
    id: 1,
    type: 'hiring', // 'hiring' | 'seeking'
    title: 'فروشنده حرفه‌ای محصولات صنعتی',
    company: 'آریا استاد',
    location: 'تهران، خیابان آزادی',
    minSalary: 15000000, // حداقل حقوق به تومان
    maxSalary: 25000000, // حداکثر حقوق به تومان
    cooperationType: 'تمام وقت',
    description: 'فروشنده حرفه‌ای با سابقه کار در حوزه صنعتی',
    date: '۱۴۰۴/۰۱/۱۵',
    tags: ['فروش', 'صنعتی', 'حقوق بالا'],
    image: '/images/jobs/job1.jpg',
    isFeatured: true,
    isVerified: true,
    // ویژگی‌های جدید
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: false,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۳ تا ۵ سال',
    education: 'لیسانس',
    gender: 'آقا / خانم',
    ageRange: '۲۵ تا ۴۰ سال'
  },
  {
    id: 2,
    type: 'seeking', // کارجو
    title: 'بازاریاب دیجیتال با ۳ سال سابقه',
    company: 'رضا محمدی',
    location: 'تهران، سعادت‌آباد',
    minSalary: null, // کارجو حقوق درخواستی ندارد
    maxSalary: null,
    cooperationType: 'پاره وقت',
    description: 'بازاریاب دیجیتال با تسلط بر شبکه‌های اجتماعی و سئو',
    date: '۱۴۰۴/۰۱/۱۴',
    tags: ['بازاریابی', 'دیجیتال', 'سئو'],
    image: '/images/jobs/job2.jpg',
    isFeatured: false,
    isVerified: true,
    // ویژگی‌های جدید
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۳ سال',
    education: 'کارشناسی ارشد',
    gender: 'آقا',
    ageRange: '۲۸ سال'
  },
  {
    id: 3,
    type: 'hiring',
    title: 'مشاور فروش',
    company: 'آریا استاد',
    location: 'اصفهان، خیابان چهارباغ',
    minSalary: 12000000,
    maxSalary: 18000000,
    cooperationType: 'تمام وقت',
    description: 'مشاور فروش با تجربه در حوزه ساختمان',
    date: '۱۴۰۴/۰۱/۱۳',
    tags: ['مشاوره', 'فروش', 'ساختمان'],
    image: '/images/jobs/job3.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: true,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۲ تا ۴ سال',
    education: 'لیسانس',
    gender: 'آقا',
    ageRange: '۳۰ تا ۴۵ سال'
  },
  {
    id: 4,
    type: 'seeking',
    title: 'مدیر فروش منطقه‌ای با ۷ سال تجربه',
    company: 'سارا احمدی',
    location: 'شیراز، خیابان معلم',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'تمام وقت',
    description: 'مدیر فروش با سابقه مدیریت تیم و افزایش فروش',
    date: '۱۴۰۴/۰۱/۱۲',
    tags: ['مدیریت', 'فروش', 'رهبری'],
    image: '/images/jobs/job4.jpg',
    isFeatured: false,
    isVerified: false,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۷ سال',
    education: 'کارشناسی',
    gender: 'خانم',
    ageRange: '۳۵ سال'
  },
  {
    id: 5,
    type: 'hiring',
    title: 'کارشناس فروش تلفنی',
    company: 'آریا استاد',
    location: 'تهران، خیابان ولیعصر',
    minSalary: 8000000,
    maxSalary: 15000000,
    cooperationType: 'تمام وقت',
    description: 'کارشناس فروش تلفنی با مهارت ارتباطی بالا',
    date: '۱۴۰۴/۰۱/۱۱',
    tags: ['فروش تلفنی', 'ارتباطات', 'مهارت کلامی'],
    image: '/images/jobs/job5.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: false,
    hasTransportation: false,
    hasMeal: false,
    hasBonus: true,
    hasFlexibleHours: true,
    hasRemoteWork: false,
    experience: '۱ تا ۳ سال',
    education: 'دیپلم',
    gender: 'آقا / خانم',
    ageRange: '۲۰ تا ۳۵ سال'
  },
  {
    id: 6,
    type: 'seeking',
    title: 'بازاریاب شبکه‌های اجتماعی',
    company: 'محمد رضایی',
    location: 'مشهد، خیابان احمدآباد',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'پاره وقت',
    description: 'بازاریاب با تسلط بر اینستاگرام و لینکدین',
    date: '۱۴۰۴/۰۱/۱۰',
    tags: ['بازاریابی', 'شبکه‌های اجتماعی', 'دیجیتال'],
    image: '/images/jobs/job6.jpg',
    isFeatured: false,
    isVerified: false,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۲ سال',
    education: 'کارشناسی',
    gender: 'آقا',
    ageRange: '۲۶ سال'
  },
  {
    id: 7,
    type: 'hiring',
    title: 'نماینده فروش لوازم پزشکی',
    company: 'آریا استاد',
    location: 'تهران، خیابان انقلاب',
    minSalary: 18000000,
    maxSalary: 28000000,
    cooperationType: 'تمام وقت',
    description: 'نماینده فروش با سابقه در حوزه تجهیزات پزشکی',
    date: '۱۴۰۴/۰۱/۰۹',
    tags: ['پزشکی', 'فروش', 'تجهیزات'],
    image: '/images/jobs/job7.jpg',
    isFeatured: true,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: true,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۳ تا ۵ سال',
    education: 'کارشناسی',
    gender: 'آقا / خانم',
    ageRange: '۲۸ تا ۴۰ سال'
  },
  {
    id: 8,
    type: 'seeking',
    title: 'کارشناس فروش اینترنتی',
    company: 'زهرا کریمی',
    location: 'اصفهان، خیابان سپاه',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'دورکاری',
    description: 'کارشناس فروش اینترنتی با آشنایی با فروشگاه‌های آنلاین',
    date: '۱۴۰۴/۰۱/۰۸',
    tags: ['اینترنتی', 'فروش', 'آنلاین'],
    image: '/images/jobs/job8.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۴ سال',
    education: 'کارشناسی ارشد',
    gender: 'خانم',
    ageRange: '۳۰ سال'
  },
  {
    id: 9,
    type: 'hiring',
    title: 'مدیر فروش بین‌الملل',
    company: 'آریا استاد',
    location: 'تهران، خیابان ونک',
    minSalary: 30000000,
    maxSalary: 45000000,
    cooperationType: 'تمام وقت',
    description: 'مدیر فروش بین‌الملل با تسلط به زبان انگلیسی',
    date: '۱۴۰۴/۰۱/۰۷',
    tags: ['بین‌الملل', 'فروش', 'مدیریت'],
    image: '/images/jobs/job9.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: true,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۵ تا ۸ سال',
    education: 'کارشناسی ارشد',
    gender: 'آقا / خانم',
    ageRange: '۳۵ تا ۵۰ سال'
  },
  {
    id: 10,
    type: 'seeking',
    title: 'مشاور فروش بیمه',
    company: 'علی حسینی',
    location: 'شیراز، خیابان زند',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'پاره وقت',
    description: 'مشاور فروش بیمه با سابقه در حوزه بیمه',
    date: '۱۴۰۴/۰۱/۰۶',
    tags: ['بیمه', 'مشاوره', 'فروش'],
    image: '/images/jobs/job10.jpg',
    isFeatured: false,
    isVerified: false,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۳ سال',
    education: 'کارشناسی',
    gender: 'آقا',
    ageRange: '۳۲ سال'
  },
  {
    id: 11,
    type: 'hiring',
    title: 'کارشناس فروش خودرو',
    company: 'آریا استاد',
    location: 'تهران، خیابان نیاوران',
    minSalary: 20000000,
    maxSalary: 35000000,
    cooperationType: 'تمام وقت',
    description: 'کارشناس فروش خودرو با دانش فنی خودرو',
    date: '۱۴۰۴/۰۱/۰۵',
    tags: ['خودرو', 'فروش', 'فنی'],
    image: '/images/jobs/job11.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: false,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۲ تا ۴ سال',
    education: 'کاردانی',
    gender: 'آقا',
    ageRange: '۲۵ تا ۳۵ سال'
  },
  {
    id: 12,
    type: 'seeking',
    title: 'بازاریاب محتوایی',
    company: 'نازنین رحیمی',
    location: 'مشهد، خیابان امامت',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'دورکاری',
    description: 'بازاریاب محتوایی با مهارت در تولید محتوا',
    date: '۱۴۰۴/۰۱/۰۴',
    tags: ['تولید محتوا', 'بازاریابی', 'نوشتن'],
    image: '/images/jobs/job12.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۲ سال',
    education: 'کارشناسی',
    gender: 'خانم',
    ageRange: '۲۷ سال'
  },
  {
    id: 13,
    type: 'hiring',
    title: 'مدیر فروش فروشگاهی',
    company: 'آریا استاد',
    location: 'تهران، خیابان جمهوری',
    minSalary: 25000000,
    maxSalary: 35000000,
    cooperationType: 'تمام وقت',
    description: 'مدیر فروش با تجربه مدیریت فروشگاه',
    date: '۱۴۰۴/۰۱/۰۳',
    tags: ['مدیریت', 'فروشگاه', 'فروش'],
    image: '/images/jobs/job13.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: true,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۴ تا ۶ سال',
    education: 'لیسانس',
    gender: 'آقا / خانم',
    ageRange: '۳۰ تا ۴۵ سال'
  },
  {
    id: 14,
    type: 'seeking',
    title: 'کارشناس فروش آنلاین',
    company: 'مهدی نوروزی',
    location: 'اصفهان، خیابان نقش جهان',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'پاره وقت',
    description: 'کارشناس فروش آنلاین با آشنایی با دیجیتال مارکتینگ',
    date: '۱۴۰۴/۰۱/۰۲',
    tags: ['دیجیتال', 'فروش', 'آنلاین'],
    image: '/images/jobs/job14.jpg',
    isFeatured: false,
    isVerified: false,
    hasInsurance: null,
    hasExperience: false,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۱ سال',
    education: 'کارشناسی',
    gender: 'آقا',
    ageRange: '۲۴ سال'
  },
  {
    id: 15,
    type: 'hiring',
    title: 'نماینده فروش صنعتی',
    company: 'آریا استاد',
    location: 'تهران، خیابان سهروردی',
    minSalary: 18000000,
    maxSalary: 28000000,
    cooperationType: 'تمام وقت',
    description: 'نماینده فروش با سابقه در حوزه صنعت',
    date: '۱۴۰۴/۰۱/۰۱',
    tags: ['صنعتی', 'فروش', 'تخصصی'],
    image: '/images/jobs/job15.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: true,
    hasBonus: true,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۳ تا ۵ سال',
    education: 'کاردانی',
    gender: 'آقا',
    ageRange: '۲۸ تا ۴۰ سال'
  },
  {
    id: 16,
    type: 'seeking',
    title: 'سرپرست تیم فروش با ۵ سال سابقه',
    company: 'فاطمه موسوی',
    location: 'تهران، خیابان فرشته',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'تمام وقت',
    description: 'سرپرست تیم فروش با حداقل ۵ سال سابقه',
    date: '۱۴۰۳/۱۲/۲۸',
    tags: ['سرپرستی', 'فروش', 'مدیریت تیم'],
    image: '/images/jobs/job16.jpg',
    isFeatured: true,
    isVerified: true,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۵ سال',
    education: 'کارشناسی ارشد',
    gender: 'خانم',
    ageRange: '۳۵ سال'
  },
  {
    id: 17,
    type: 'hiring',
    title: 'بازاریاب اینفلوئنسری',
    company: 'آریا استاد',
    location: 'تهران، خیابان جردن',
    minSalary: 12000000,
    maxSalary: 22000000,
    cooperationType: 'دورکاری',
    description: 'بازاریاب اینفلوئنسری با ارتباط با برندها',
    date: '۱۴۰۳/۱۲/۲۷',
    tags: ['اینفلوئنسر', 'بازاریابی', 'شبکه‌های اجتماعی'],
    image: '/images/jobs/job17.jpg',
    isFeatured: false,
    isVerified: false,
    hasInsurance: false,
    hasExperience: false,
    hasTransportation: false,
    hasMeal: false,
    hasBonus: false,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۱ تا ۲ سال',
    education: 'دیپلم',
    gender: 'آقا / خانم',
    ageRange: '۱۸ تا ۲۵ سال'
  },
  {
    id: 18,
    type: 'seeking',
    title: 'کارشناس فروش B2B',
    company: 'حمیدرضا قاسمی',
    location: 'تهران، خیابان میرزای شیرازی',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'تمام وقت',
    description: 'کارشناس فروش B2B با شبکه ارتباطی قوی',
    date: '۱۴۰۳/۱۲/۲۶',
    tags: ['B2B', 'فروش', 'ارتباطات'],
    image: '/images/jobs/job18.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۴ سال',
    education: 'کارشناسی',
    gender: 'آقا',
    ageRange: '۳۰ سال'
  },
  {
    id: 19,
    type: 'hiring',
    title: 'مشاور بازاریابی دیجیتال',
    company: 'آریا استاد',
    location: 'تهران، خیابان پاسداران',
    minSalary: 25000000,
    maxSalary: 40000000,
    cooperationType: 'پاره وقت',
    description: 'مشاور بازاریابی دیجیتال با دانش سئو و تولید محتوا',
    date: '۱۴۰۳/۱۲/۲۵',
    tags: ['دیجیتال', 'مشاوره', 'سئو'],
    image: '/images/jobs/job19.jpg',
    isFeatured: false,
    isVerified: true,
    hasInsurance: true,
    hasExperience: true,
    hasTransportation: true,
    hasMeal: false,
    hasBonus: true,
    hasFlexibleHours: true,
    hasRemoteWork: true,
    experience: '۳ تا ۶ سال',
    education: 'کارشناسی ارشد',
    gender: 'آقا / خانم',
    ageRange: '۳۰ تا ۴۵ سال'
  },
  {
    id: 20,
    type: 'seeking',
    title: 'مدیر برند با سابقه درخشان',
    company: 'الناز صفری',
    location: 'تهران، خیابان ولیعصر',
    minSalary: null,
    maxSalary: null,
    cooperationType: 'تمام وقت',
    description: 'مدیر برند با سابقه در برندهای معتبر',
    date: '۱۴۰۳/۱۲/۲۴',
    tags: ['برند', 'مدیریت', 'بازاریابی'],
    image: '/images/jobs/job20.jpg',
    isFeatured: true,
    isVerified: true,
    hasInsurance: null,
    hasExperience: true,
    hasTransportation: null,
    hasMeal: null,
    hasBonus: null,
    hasFlexibleHours: false,
    hasRemoteWork: false,
    experience: '۶ سال',
    education: 'کارشناسی ارشد',
    gender: 'خانم',
    ageRange: '۳۸ سال'
  }
]